# Use the latest travis infrastructure
sudo: false

# We use node
language: node_js
sudo: false
node_js:
  - "7"
  - "6"
  - "5"
install:
  - npm install -g
script:
  - npm test
cache:
  directories:
    - node_modules
