version: 1.0.{build}

clone_depth: 1
clone_folder: c:\projects\brace_umd
notifications:
- provider: Email
  to:
  - robertsteckroth@gmail.com
  subject: A Brace UMD build has failed.
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false


environment:
  matrix:
    - nodejs_version: 5
    - nodejs_version: 6
    - nodejs_version: 7
    - nodejs_version: 8
    - nodejs_version: 9

install:
  - npm install

build: off

test_script:
  - node --version && npm --version
  - npm test

matrix:
  fast_finish: false
